name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codice
        uses: actions/checkout@v4

      - name: Installa Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      - name: Ricrea progetto Android
        run: flutter create --project-name buco .

      - name: Installa dipendenze
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Carica APK
        uses: actions/upload-artifact@v4
        with:
          name: buco-apk
          path: build/app/outputs/flutter-apk/app-release.apk
